name: primer_parcial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  collection: 1.18.0
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.6
  image_picker: ^1.1.2
  my_library: ^0.0.1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.1.2
  floor_generator: ^1.4.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/1/
    - assets/2/
    - assets/3/
    - assets/4/
